# -*- coding: utf-8 -*-
"""
Created on Fri Nov  5 16:40:35 2021

@author: Admin
"""

print("Days are waiting me that I wait")
print("At five oc'lock we will meet at Italian retourant")
print('Ohh my future husband,Iam saving clean myself for you , and you must keeep you for me too')
print("I dont't have right for falling,becouse more people are counting me")
print('I am stadying at "2109"group')
print ("we will meet at 5 \no'clock")
print('we will meet at 5 o\'clock')
print('what time is best for you? Of course 5 o\'clock55')
print('Ilmdan boshqa najot yo\'q,va bo\'lmaydi ham')
print("Ilmdan boshqa najot \nyo'q,bo'lmaydi ham")
print('yaxshi insonlar o\'lmaydi,ularning xotirasi mangu qoladi')
print("Yaxshi insonlar \no'lmaydi ularning xotirasi mangu yashaydi")
print(19/5)
print(5*4)
print(75+41*6/2)
print(15//3)
print(19//5)
print(28//3)
print(2**9)
print(2**5/8)
print(8**2//3-9+11)
print(8%3)
print(27%3)
print(28%5)
print("To'qqizning kvadrati", 9**2, "ga teng")
print("Beshning kvadrati",5**2 ,"ga teng")
print("9ning kvadrati",9**2,"ga teng")
print("\nO'n beshning kubi",15**3,"ga teng")
print("10 ga 10 ni qo'shsak",10+10,"bo'ladi")
print('o\'nga o\'nni qo\'shsak',10+10,'bo\'ladi')
print("\no'nga o'nni qo'shsak",10+10,"\nbo'ladi")
print('3*3')
print(2*5*3.14159)
print(5**5*3.14149)
print(5**2*3.14159)
print("mening ismim Sevara")
print('mening ismim S #men dasturchiman')
print('"Matiz","tico",\'damas\' ko\'rgan qilar havas')
print(5**4)
print(22%4)
print("kvadrad yuzi",125**2,"kvadrat peremetri",125*4,"bo'ladi")
print(6**2*3.14)
print(6**2+7**2)
print("Katetlari 8 va 7 bo'lgan to'g'ri burchakli uchburchakning gipotenuzasi", (6**2+7**2)**(1/2))
print(85**(1/2))
print("diametri 12 bo'lgan aylananing yuzi",(12/2)**2*3.14,"bo'ladi")
